# Generated by Django 2.2.4 on 2019-08-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.IntegerField(unique=True)),
                ('investName', models.CharField(max_length=100)),
                ('investRequire', models.BigIntegerField()),
                ('calledDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('committedDate', models.DateField()),
                ('amount', models.BigIntegerField()),
            ],
            options={
                'ordering': ['committedDate'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundInvest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investAmount', models.BigIntegerField()),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Call')),
                ('commit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Commitment')),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fund')),
            ],
        ),
        migrations.AddField(
            model_name='commitment',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fund'),
        ),
    ]
