# Generated by Django 2.2.4 on 2019-08-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190831_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
